version: '3.8'

services:
  sentinela-web:
    build: .
    container_name: chatwoot-sentinela
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./database:/app/database
    networks:
      - kluh-network

networks:
  kluh-network:
    driver: bridge